### ISSUE TITLE
Uncaught Error: Call to undefined method TransportRequestException::getErrorCode()

### ISSUE THREAD

**Issue by zavaruev** [crmagent-developers/opencart-vk-module#3]
Пытаюсь выгрузить каталог, выполняю /path_to_opencart/system/vk_cron/exportOffer.php
получаю:
PHP Fatal error:  Uncaught Error: Call to undefined method TransportRequestException::getErrorCode() in /path_to_opencart/system/library/vk/VkApiRequest.php:134
Stack trace:
#0 /path_to_opencart/system/library/vk/vk.php(443): VkApiRequest->upload('https://pu.vk.c...', 'photo', '/home/admin/web...')
#1 /path_to_opencart/system/library/vk/vk.php(333): VK\vk->loadPhoto(Array, '')
#2 /path_to_opencart/system/library/vk/vk.php(635): VK\vk->getImageId('', '29676*0', 'product_main_ph...')
#3 /path_to_opencart/admin/controller/extension/module/vk.php(366): VK\vk->addProducts(Array)
#4 /path_to_opencart/system/storage/modification/system/engine/action.php(51): ControllerExtensionModuleVk->exportOffer()
#5 /path_to_opencart/system/storage/modification/system/engine/front.php(70): Action->execute(Object(Registry))
#6 /path_to_opencart/system in /path_to_opencart/system/library/vk/VkApiRequest.php on line 134

PHP 7.0.33

**Comment by denisneposeda** [comment]
@zavaruev проверяй изображения на соответствие условий:
Соответствует ли картинка требованиям? Минимальный размер фото — 400 × 400 px, сумма высоты и ширины — не более 14 000 px, объём файла — не более 50 Мбайт, соотношение сторон — не менее 1:20. Допустимые форматы: JPG, PNG, GIF.

**Comment by zavaruev** [comment]
Придется php вспоминать( Жаль, что из коробки модуль не справляется даже с примитивными проблемами.

**Comment by denisneposeda** [comment]
@zavaruev я думаю достаточно найти, где берутся изображения и применить стандартную функцию от OC для изображений...правда она кривая)))

**Comment by denisneposeda** [comment]
@zavaruev, потестился - еще проблема может быть из-за изображений категорий (тоже некоректные).
Еще такая проблема может быть при баге - когда запустился экспорт, но товары удаляются в ВК, то запись о изображениях хранится в БД `oc_vk_images`.

Короче что бы все было гудя для загрузки:
1. Забираешь с БД - основные фото товаров и категорий
2. Проверяешь все на условия PHP
3. Если уже был экспорт - убрать все категории, и запустить экспорт, что бы оно подчистило товары и подборки модулем
4. Перепроверить таблицы oc_vk_images, oc_vk_products что бы были чистые
5. Запуск

Мдамс не думал, что за запуск готово модуля потрачу пол дня.

**Comment by TimurTurdyev** [comment]
Поправил https://github.com/crmagent-developers/opencart-vk-module/pull/7 
И добавил поддержку opencart 3
